import { Listing } from "./types";

// Demo veriler. Sahibinden.com API entegrasyonu bağlandığında bu liste
// gerçek ilan verisiyle (fiyat, m2, oda sayısı, ilan linki vb.) değiştirilecek.
export const listings: Listing[] = [
  {
    id: "mesby-1001",
    title: "Mesby Panorama Konutları'nda Satılık 3+1",
    price: 4250000,
    currency: "TL",
    m2: 145,
    rooms: "3+1",
    floor: "6. Kat",
    buildingAge: "0 (Yeni)",
    district: "Ataşehir",
    city: "İstanbul",
    isNew: true,
    publishedAt: "2026-07-02",
    art: 1,
  },
  {
    id: "mesby-1002",
    title: "Kadıköy'de Satılık Deniz Manzaralı 2+1",
    price: 3100000,
    currency: "TL",
    m2: 95,
    rooms: "2+1",
    floor: "3. Kat",
    buildingAge: "5-10",
    district: "Kadıköy",
    city: "İstanbul",
    isNew: false,
    publishedAt: "2026-06-21",
    art: 2,
  },
  {
    id: "mesby-1003",
    title: "Mesby Bahçe Konakları'nda Bahçe Katı 4+1",
    price: 6750000,
    currency: "TL",
    m2: 210,
    rooms: "4+1",
    floor: "Bahçe Katı",
    buildingAge: "5-10",
    district: "Sancaktepe",
    city: "İstanbul",
    isNew: false,
    publishedAt: "2026-06-14",
    art: 3,
  },
  {
    id: "mesby-1004",
    title: "Üsküdar'da Yatırımlık Satılık 1+1",
    price: 2450000,
    currency: "TL",
    m2: 65,
    rooms: "1+1",
    floor: "2. Kat",
    buildingAge: "10-15",
    district: "Üsküdar",
    city: "İstanbul",
    isNew: false,
    publishedAt: "2026-05-30",
    art: 4,
  },
  {
    id: "mesby-1005",
    title: "Çekmeköy Vadi Evleri'nde Satılık 3+1 Dubleks",
    price: 3850000,
    currency: "TL",
    m2: 130,
    rooms: "3+1",
    floor: "Dubleks",
    buildingAge: "0 (Yeni)",
    district: "Çekmeköy",
    city: "İstanbul",
    isNew: true,
    publishedAt: "2026-07-06",
    art: 5,
  },
  {
    id: "mesby-1006",
    title: "Maltepe Sahil Hattına Yakın Satılık 5+1",
    price: 8900000,
    currency: "TL",
    m2: 260,
    rooms: "5+1",
    floor: "8. Kat",
    buildingAge: "0 (Yeni)",
    district: "Maltepe",
    city: "İstanbul",
    isNew: true,
    publishedAt: "2026-07-08",
    art: 6,
  },
];

export const SAHIBINDEN_STORE_URL = "https://www.sahibinden.com/";
